# name: Docker Image CI

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build the Docker image
#         run: docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/calendario:${GITHUB_REF##*/}
#       - name: Push the Docker image
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/calendario:${GITHUB_REF##*/}
